global:
  config:
    argoNamespace: psc-argocd-config-central
    spec:
      destination:
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/marlondaraujo/argocluster
        targetRevision: main

apps:
- name: argo-central-9vr7rvjwx6wcp4v7-9vr7rvjwx6wcp4v7-9vr7rvjwx6wcp4v7-9vr7rvjwx6wcp4v7-9vr7rvjwx6wcp4v7-f9vr7rvjwx6wcp4v7-f9vr7rvjwx6wcp4v7-f9vr7rvjwx6wcp4v7-f9vr7rvjwx6wcp4v7-f9vr7rvjwx6wcp4v7-f
  tool:
    helm:
      releaseName: argo-central

- name: prometheus
  tool:
    helm:
      releaseName: prometheus

- name: gogs
