global:
  config:
    argoNamespace: argocd-bootstrap
    spec:
      destination:
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/marlondaraujo/argocluster
        targetRevision: main

apps:
- name: argo-central
  tool:
    helm:
      releaseName: argo-central
