apiVersion: v1
kind: Secret
metadata:
  name: vcluster2
  namespace: psc-argocd-config-central
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: vcluster2
  server: https://vcluster2.vcluster2.svc.cluster.local:443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ik9xMFdGUTRhREFBV2h4RnFXT1dJeVJOcUNlMGlab18td1RFRk9kSHBxSmsifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzY2NTM5MjI0LCJpYXQiOjE3NjY1MzU2MjQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYWE3MGJjNDEtYzk5MC00OTUyLWI1OTQtMmE1MjE3MTkwYzMyIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhcmdvY2QtbWFuYWdlciIsInVpZCI6IjhlYTVjNjY5LTgzNTAtNGY3Ny04MDdhLTA4MzM3NmZlY2JkZCJ9fSwibmJmIjoxNzY2NTM1NjI0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YXJnb2NkLW1hbmFnZXIifQ.ZLCgDvOsTLdVeq_8BPA9fMOdwv5LEwybq9rtiYTiNJXw5Z0z6TQVwWbsV241-aVx-8Yo1zgvKbdK_ZNX-Mt3M-ej0UikDCDUWk8nCm-MkeuyTp-LJKLA1SehZlXI8IEdYgn9Lng8MG-tuTV1mrbzFDoEiYiqd9k38Rs6uTf6KiiNlhSXyJ5QHP2XQ96vuAuTFtKBwXmloGbcknqHTJvLF5eJNG0g4VLcfYeGp4Te5No-Pkx-5vRvPFMq6dqaLnqgTcbfpMWlW7I2L0EYvyTp7oHuLFTpalt9Kboe2QNO0QxE7LI3i8b-dvFpN0kdODYuaPKyjMXfJmw-5lzSE7TpXw",
      "tlsClientConfig": {
        "insecure": true
      }
    }